security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email 

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthentificatorAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true  
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                target: app_login

            entry_point: form_login
